name: Build Standalone Executables

on:
  push:
    branches:
      - master
  workflow_dispatch: # Memungkinkan Anda memicu build secara manual dari tombol di GitHub

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build Executable
        run: python build_exe.py

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: Scrapiky-Windows-EXE
          path: server/dist/Scrapiky.exe

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build Executable
        run: python build_exe.py

      - name: Upload Linux Executable
        uses: actions/upload-artifact@v4
        with:
          name: Scrapiky-Linux-App
          path: server/dist/Scrapiky
